[general]
img_width = 1024
img_height = 1448
header_ratio = 0.25
footer_ratio = 0.25
pct_vs_template_treshold = 2.4

[debug]
mode = true
output_dir = "./out"

[rects]
"1385" = [0.048, 0.71, 0.248, 0.082]
"1301-2022" = [0.032, 0.921, 0.149, 0.034]
"1344" = [0.3, 0.64, 0.354, 0.21]
"1344-2020" = [0.3, 0.64, 0.354, 0.21]
"1344-2021" = [0.3, 0.64, 0.354, 0.21]
"1344-2022" = [0.3, 0.64, 0.354, 0.21]
"1344-2023" = [0.3, 0.64, 0.354, 0.21]

# --- NEW: which pages to include per form type ---
[include_map]
"1385"       = [1]
"1301-2022"  = [1]
"1344-2020"  = [1]
"1344-2021"  = [1]
"1344-2022"  = [1]
"1344-2023"  = [1]

[signature_thresholds]
# Score bands:
#   score < maybe_lower            -> none
#   maybe_lower <= score < yes_lower -> review
#   score >= yes_lower             -> present
maybe_lower = 0.6
yes_lower   = 0.7

[sign_labels]
# You can rename these three labels freely:
none    = "none"
review  = "review"
present = "present"
