[general]
img_width = 596                 # 596
img_height = 842                # 842
pct_vs_template_treshold = 10.0

[templates]
# Default values for any template not listed below
default_header_ratio = 0.25
default_footer_ratio = 0.25

[templates.settings]
# Specific overrides can be added here.
# The key must match the PDF filename in your templates_pdf folder.
# Example: For "134.pdf", the key is "134".
"134" = { header_ratio = 0.15, footer_ratio = 0.20 }
"901" = { header_ratio = 0.30, footer_ratio = 0.30 }

[debug]
mode = true
output_dir = "./out"

[rects]
"134" = [35, 674, 117, 35]
"150" = [30, 778, 88, 43]
"901" = [130, 693, 100, 35]
"901a" = [133, 587, 90, 40]
"1213" = [357, 781, 105, 40]
"1227-2022" = [27, 792, 90, 38]
"1229" = [152, 625, 107, 45]
"1344-2022" = [222, 642, 120, 75]
"1345" = [30, 423, 105, 55]
"1346" = [35, 640, 100, 45]
"1385" = [32, 615, 120, 50]
"1485" = [40, 690, 115, 35]
"1504" = [30, 713, 115, 52]
"1585" = [135, 735, 90, 30]

# --- NEW: which pages to include per form type ---
[include_map]
"134" = [2]
"150" = [1]
"901" = [1]
"901a" = [1]
"1213" = [2]
"1227-2022" = [1]
"1229" = [1]
"1344-2022" = [1]
"1345" = [1]
"1346" = [3]
"1385" = [1]
"1485" = [1]
"1504" = [1]
"1585" = [1]

[signature_thresholds]
# Score bands:
# score < maybe_lower -> none
# maybe_lower <= score < yes_lower -> review
# score >= yes_lower -> present
maybe_lower = 0.6
yes_lower = 0.7

[sign_labels]
# You can rename these three labels freely:
none = "none"
review = "review"
present = "present"

[pipeline]
splitting_only = false # set to true to do ONLY PDF -> images
